### ISSUE TITLE
TypeError: Cannot read property 'filtersop' of undefined

### ISSUE THREAD

**Issue by thatbudakguy** [ExLibrisGroup/primo-explore-devenv#10]
```
TypeError: Cannot read property 'filtersop' of undefined                        angular.js:13642
```
on load, I get a grey screen. devtools javascript console shows the above error.

**Comment by noamamit92** [comment]
The error above is not the issue - can you send me the output of your console and your PROXY_SERVER setup in config.js

**Comment by thatbudakguy** [comment]
nothing else appears in chrome's javascript console.
my config.js:
```
var PROXY_SERVER = 'http://alliance-primo-sb.hosted.exlibrisgroup.com/';
```
output of `gulp run --view CENTRAL_PACKAGE`:
```
[14:21:22] Using gulpfile ~/web/alliance-newui-dev/gulpfile.js
[14:21:22] Starting 'connect:primo_explore'...
[14:21:23] Finished 'connect:primo_explore' after 58 ms
[14:21:23] Starting 'watch-js'...
[14:21:23] Finished 'watch-js' after 8.15 ms
[14:21:23] Starting 'setup_watchers'...
[14:21:23] Finished 'setup_watchers' after 3.65 ms
[14:21:23] Starting 'custom-js'...
[14:21:23] 'custom-js' errored after 757 μs
[14:21:23] TypeError: buildParams.customNpmJsModulePath is not a function
    at Gulp.<anonymous> (/Users/budak/web/alliance-newui-dev/gulp/tasks/buildCustomJs.js:24:151)
    at module.exports (/Users/budak/web/alliance-newui-dev/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/budak/web/alliance-newui-dev/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/budak/web/alliance-newui-dev/node_modules/orchestrator/index.js:214:10)
    at /Users/budak/web/alliance-newui-dev/node_modules/orchestrator/index.js:279:18
    at finish (/Users/budak/web/alliance-newui-dev/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/Users/budak/web/alliance-newui-dev/node_modules/orchestrator/lib/runTask.js:60:3)
    at Gulp.Orchestrator._runTask (/Users/budak/web/alliance-newui-dev/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/budak/web/alliance-newui-dev/node_modules/orchestrator/index.js:214:10)
    at /Users/budak/web/alliance-newui-dev/node_modules/orchestrator/index.js:279:18
    at finish (/Users/budak/web/alliance-newui-dev/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/Users/budak/web/alliance-newui-dev/node_modules/orchestrator/lib/runTask.js:60:3)
    at Gulp.Orchestrator._runTask (/Users/budak/web/alliance-newui-dev/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/budak/web/alliance-newui-dev/node_modules/orchestrator/index.js:214:10)
    at /Users/budak/web/alliance-newui-dev/node_modules/orchestrator/index.js:279:18
    at finish (/Users/budak/web/alliance-newui-dev/node_modules/orchestrator/lib/runTask.js:21:8)
[BS] Access URLs:
 --------------------------------------
       Local: http://localhost:8003
    External: http://149.175.20.94:8003
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://149.175.20.94:3001
 --------------------------------------
[BS] Serving files from: primo-explore
```

**Comment by noamamit92** [comment]
Can you try this (from another issue)? And change the proxy to:


var PROXY_SERVER = 'http://alliance-primo-sb.hosted.exlibrisgroup.com:80';
I updated the :
https://github.com/ExLibrisGroup/primo-explore-devenv/blob/master/gulp/config.js
File - if you can update your enviornment and let me know the outcome

**Comment by thatbudakguy** [comment]
that resolved `TypeError: buildParams.customNpmJsModulePath is not a function`, but I still have a grey screen (nothing is visible in the browser). Now my console output is:
```shell
[10:15:03] Using gulpfile ~/web/alliance-newui-dev/gulpfile.js
[10:15:03] Starting 'connect:primo_explore'...
[10:15:03] Finished 'connect:primo_explore' after 54 ms
[10:15:03] Starting 'watch-js'...
[10:15:03] Finished 'watch-js' after 7.69 ms
[10:15:03] Starting 'setup_watchers'...
[10:15:03] Finished 'setup_watchers' after 2.65 ms
[10:15:03] Starting 'custom-js'...
[10:15:03] Starting 'custom-css'...
[10:15:03] Finished 'custom-js' after 30 ms
[10:15:03] Finished 'custom-css' after 16 ms
[10:15:03] Starting 'run'...
[10:15:03] Finished 'run' after 7.94 μs
[BS] Access URLs:
 --------------------------------------
       Local: http://localhost:8003
    External: http://149.175.20.94:8003
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://149.175.20.94:3001
 --------------------------------------
[BS] Serving files from: primo-explore
custom/CENTRAL_PACKAGE
{ viewJs: [ 'custom/CENTRAL_PACKAGE/js/custom.js' ],
  viewCss: [ 'custom/CENTRAL_PACKAGE/css/custom1.css' ],
  centralCss: [ 'custom/CENTRAL_PACKAGE/css/custom1.css' ],
  favIcon: [],
  libraryLogo: undefined,
  resourceIcons: {},
  homepageHtml: { en_US: 'custom/CENTRAL_PACKAGE/html/home_en_US.html' } }
```
javascript devtools still says:
```javascript
bundle-e5d34a30c2.js:16 TypeError: Cannot read property 'filtersop' of undefined
```

**Comment by thatbudakguy** [comment]
same result in incognito & re-running `gulp run --view CENTRAL_PACKAGE`.

**Comment by noamamit92** [comment]
I think this is the correct workflow:


1, set config.js:

var PROXY_SERVER = 'http://alliance-primo-sb.hosted.exlibrisgroup.com:80';

2. in the BO set any view(i.e: WSU_TEST) to : 
Inherit from Central package  

3. start your server against this view using:
gulp run --view WSU_TEST


4. now develop your CENTRAL_PACKAGE folder in the development enviornment

**Comment by thatbudakguy** [comment]
This works if I change the name of the CENTRAL_PACKAGE folder to the view I'm using (LCC_PCCWG) - thanks.

However, is it a good workflow for developing the CENTRAL_PACKAGE folder? Can I just take the resulting package and upload it to the BO as a central package? I'm trying to work on a consortium-level package rather than a institution's view.

**Comment by noamamit92** [comment]
Ill have to rethink the workflow but in general there is no real central
view so you always need to use a real view in the url, the name of the
package folder is really not important

**Comment by thatbudakguy** [comment]
OK, thanks for explanation 👍 
closing.
