### ISSUE TITLE
"SyntaxError: Unexpected end of JSON input" causes environment to stop running when starting up

### ISSUE THREAD

**Issue by ianchan** [ExLibrisGroup/primo-explore-devenv#126]
I'm encountering the following error when I run "gulp run --view _<viewname>_" I've been using this for several years now and have not come across this before. I updated to the most recent release in January and did not encounter problems after that. Here is the error message:

`SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/Users/ichan/Documents/Sites/webserver/primo-explore-devenv/gulp/tasks/08-servers.js:59:53)
    at IncomingMessage.emit (events.js:194:15)
    at IncomingMessage.EventEmitter.emit (domain.js:459:23)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

Any help I could get with resolving this would be greatly appreciated.

**Comment by ianchan** [comment]
It started working late yesterday. Perhaps it was a network glitch. I thought initially switching browsers was the reason it started working but that seems unlikely.
