### ISSUE TITLE
Location of colors.json

### ISSUE THREAD

**Issue by kloevschall** [ExLibrisGroup/primo-explore-devenv#24]
I am unable to follow Noam's css Recipe 1 - Color Scheme from the handouts at New UI Hackathon / Virtual Conference: Dec. 12 - Dec. 16.

"Open the _colors.json_ file in the root of your view folder" - I am only able to get this to work if the _colors.json_ file is within the root of the development environment. Thus one _colors.json_ to rule all views and not one per view. And this seems wrong.

If I move _colors.json_ to the view folder the deployment fails:

```
D:\PrimoDev\primo-explore-devenv-master\primo-explore\custom\desktop>gulp app-css --view desktop
...
...
[10:07:03] Error: ENOENT: no such file or directory, open 'D:\PrimoDev\primo-explore-devenv-master\colors.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Gulp.gulp.task (D:\PrimoDev\primo-explore-devenv-master\gulp\tasks\build-scss.js:41:39)
    at module.exports (D:\PrimoDev\primo-explore-devenv-master\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\PrimoDev\primo-explore-devenv-master\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\PrimoDev\primo-explore-devenv-master\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (D:\PrimoDev\primo-explore-devenv-master\node_modules\orchestrator\index.js:134:8)
    at runNextSet (D:\PrimoDev\primo-explore-devenv-master\node_modules\run-sequence\index.js:86:16)
    at Gulp.onTaskEnd (D:\PrimoDev\primo-explore-devenv-master\node_modules\run-sequence\index.js:75:5)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (D:\PrimoDev\primo-explore-devenv-master\node_modules\orchestrator\index.js:264:8)
    at D:\PrimoDev\primo-explore-devenv-master\node_modules\orchestrator\index.js:275:23
    at finish (D:\PrimoDev\primo-explore-devenv-master\node_modules\orchestrator\lib\runTask.js:21:8)
    at D:\PrimoDev\primo-explore-devenv-master\node_modules\orchestrator\lib\runTask.js:52:4
[10:07:03] 'app-css' errored after 276 ms
[10:07:03] Error in plugin 'run-sequence(color-variables)'
Message:
    color-variables catch

**Comment by ajones3066** [comment]
Additionally, it seems there is some confusion about the specificity of the colors.json file.  If developers want to have multiple views with different color schemes, the colors.json file had to be edited and re-written.  what would be better is if there were a colors_<CUSTOM VIEW FOLDER NAME>.json. this would allow us to use the same gulp app-css command and the specific colors.json file would be applied.

**Comment by antrez770** [comment]
Hi Did somebody install addon "Report broken links" for Primo? 
Thanks for all.
