### ISSUE TITLE
TypeError: config.setBrowserify is not a function

### ISSUE THREAD

**Issue by dmoore** [ExLibrisGroup/primo-explore-devenv#58]
I'm getting the following error when attempting to gulp my view: 

```
config.setBrowserify(options.browserify);
       ^

TypeError: config.setBrowserify is not a function
    at Object.<anonymous> (/Users/Moored/Documents/primo-explore-devenv/gulpfile.js:12:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:190:9)
    at /usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:164:9
    at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:110:14
    at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:38:12
    at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:49:7
```

I've restarted from scratch but I'm still getting the error. Any tips?

**Comment by gilax** [comment]
@dmoore is that still relevant?

**Comment by dmoore** [comment]
No. Apologies, I forgot about this open issue.
