### ISSUE TITLE
Issue with bugfix #57 for build-scss.js

### ISSUE THREAD

**Issue by kloevschall** [ExLibrisGroup/primo-explore-devenv#60]
Hi

The most recent fix for #57 breaks my gulp tasks:

```
D:\PrimoDev\primo-explore-devenv\gulp\tasks>git checkout 01d7522 -- build-scss.js

D:\PrimoDev\primo-explore-devenv\gulp\tasks>gulp
[12:25:05] Working directory changed to D:\PrimoDev\primo-explore-devenv
D:\PrimoDev\primo-explore-devenv\gulp\tasks\build-scss.js:33
gulp.task('extract-scss-files', () = {
                                ^^

ReferenceError: Invalid left-hand side in assignment
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireDir (D:\PrimoDev\primo-explore-devenv\node_modules\require-dir\index.js:116:33)

```

Reverting one step back fixes the problem:

```
D:\PrimoDev\primo-explore-devenv\gulp\tasks>git checkout 11c5746 -- build-scss.js

D:\PrimoDev\primo-explore-devenv\gulp\tasks>gulp
[12:28:29] Working directory changed to D:\PrimoDev\primo-explore-devenv
[12:28:31] Using gulpfile D:\PrimoDev\primo-explore-devenv\gulpfile.js
[12:28:31] Task 'default' is not in your gulpfile
[12:28:31] Please check the documentation for proper gulpfile formatting
```

I have the most recent environment (cloned with git) and latest NodeJS LTS.

Thanks,
Kasper Løvschall

**Comment by cbaksik** [comment]
Me too. Just wasted 2 hours thinking I was doing something wrong with setting up the environment.

**Comment by noamamit92** [comment]
ficed by #60

**Comment by ajones3066** [comment]
Thanks Noam!
