### ISSUE TITLE
Fix support for Node 8

### ISSUE THREAD

**Issue by danmichaelo** [ExLibrisGroup/primo-explore-devenv#66]
Node 8 is the LTS version of Node now, so it should be supported. Currently it's not:

```
$ gulp run --view UBO --browserify
/Users/danmichael/projects/scriptotek/primo-explore-devenv/node_modules/require-dir/index.js:97
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/Users/danmichael/projects/scriptotek/primo-explore-devenv/node_modules/require-dir/index.js:97:37)
    at Object.<anonymous> (/Users/danmichael/projects/scriptotek/primo-explore-devenv/gulpfile.js:5:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Liftoff.handleArguments (/Users/danmichael/projects/scriptotek/primo-explore-devenv/node_modules/gulp/bin/gulp.js:116:3)
```

But this is easily fixed by upgrading `require-dir` from 0.3.0 to 0.3.2 [(ref)](https://github.com/aseemk/requireDir/commit/c316ad818c7c4a39a01c0436c9d20526c498bf1a)

**Comment by meinbrodt** [comment]
Thanks for the hint on how to fix this. 

+1 for the idea to include this fix
