### ISSUE TITLE
Timeout probleme & TCPConnectWrap.afterConnect

### ISSUE THREAD

**Issue by AxelDorian** [ExLibrisGroup/primo-explore-devenv#78]
Hello,

I have a problem while installing primo-explore-devenv for Primo VE.
My last command line entry  ends up with timeouts error.
I noticed that a similar problem was reported here last year (issue #9) but I could not find the appropriate solution.

When I browse to my local URL I receive the following error message:

Error: connect ETIMEDOUT 31.186.254.137:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

Can somebody help me?
Thanks a lot :-)

gulp run --view LOCAL-VIEW --ve
[08:57:23] Starting 'connect:primo_explore'...
[08:57:24] Finished 'connect:primo_explore' after 567 ms
[08:57:24] Starting 'reinstall-primo-node-modules'...
[08:57:24] Finished 'reinstall-primo-node-modules' after 28 µs
[08:57:24] Starting 'watch-js'...
[08:57:24] Finished 'watch-js' after 16 ms
[08:57:24] Starting 'watch-custom-scss'...
[08:57:24] Finished 'watch-custom-scss' after 18 µs
[08:57:24] Starting 'watch-css'...
[08:57:24] Finished 'watch-css' after 1.96 ms
[08:57:24] Starting 'setup_watchers'...
[08:57:24] Finished 'setup_watchers' after 2.75 ms
[08:57:24] Starting 'custom-html-templates'...
[08:57:24] Finished 'custom-html-templates' after 11 ms
[08:57:24] Starting 'custom-js'...
[08:57:24] Finished 'custom-js' after 6.79 ms
[08:57:24] Starting 'custom-scss'...
[08:57:24] Finished 'custom-scss' after 3.85 µs
[08:57:24] Starting 'custom-css'...
[08:57:24] Finished 'custom-css' after 25 ms
[08:57:24] Starting 'run'...
[08:57:24] Finished 'run' after 2.14 µs
[BS] Access URLs:
 ---------------------------------------
       Local: http://localhost:8003
    External: http://10.132.132.126:8003
 ---------------------------------------
          UI: http://localhost:3001
 UI External: http://10.132.132.126:3001
 ---------------------------------------
[BS] Serving files from: primo-explore
Error: connect ETIMEDOUT 31.186.254.137:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

**Comment by gilax** [comment]
hi @AxelDorian, sorry for the late response, have you manage to walk around this issue?
I may have a walk around - you can use the first url (the one with "localhost") instead of the specific address.
if you haven't solved this and my solution doesn't work for you please reopen this issue.

best regards,
Gilad
