### ISSUE TITLE
Cannot find module 'vinyl-source-stream'

### ISSUE THREAD

**Issue by cbaksik** [ExLibrisGroup/primo-explore-devenv#80]
Getting this error when running updated code (against May release) using gulp run --view XXX;

`module.js:471
    throw err;
    ^

Error: Cannot find module 'vinyl-source-stream'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/corinnabaksik/Documents/GitHub/primo-explore-devenv/gulp/tasks/buildCustomJs.js:14:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)`

**Comment by noamamit92** [comment]
Can you specify the actions taken after the sync?

Did you run
npm install
?

**Comment by cbaksik** [comment]
I hadn't done that. If that is best practice could it be added to the GitHub instructions?

I ran that and it's working now. Thanks!
