### ISSUE TITLE
local issuer certificate error while running gulp environment

### ISSUE THREAD

**Issue by rapidfire09** [ExLibrisGroup/primo-explore-devenv#92]
I got a new Windows 10 PC and tried to run gulp environment on it. I am getting the following error when I try to open http://localhost:8003/primo-explore/search?vid=01TIMF_INST_V1. 

Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:603:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)

My pc is behind a corporate proxy server. Has anybody encountered a similar issues? 

Thanks for you help. 

Neeraj

**Comment by gilax** [comment]
Hi @rapidfire09,

Is 01TIMF_INST_V1 is a valid view code in your Primo?

thanks,
Gilad

**Comment by noamamit92** [comment]
closing as it is waiting for a response for a while
